backend:
  name: git-gateway
  branch: master  # Branch to update (optional; defaults to master)

publish_mode: editorial_workflow

media_folder: "static/img" #アップロードされたファイルを保存するフォルダパス
public_folder: "/img" #アップロードされたファイルがアクセスされるフォルダパス
collections:
  - name: "post"
    label: "Post"
    folder: "content/post"
    create: true
    fields: # 管理画面に追加したいフォームを追加していく
      - {label: "タイトル", name: "Title", widget: "string"}
      - {label: "サブタイトル", name: "Subtitle", widget: "string"}
      - {label: "本文", name: "body", widget: "markdown", required: false}
      - {label: "タグ", name: "tags", widget: "text", required: false}
