backend:
  name: git-gateway
  branch: master  # Branch to update (optional; defaults to master)

publish_mode: editorial_workflow

locale: ja

media_folder: "assets/images" #アップロードされたファイルを保存するフォルダパス
public_folder: "/img" #アップロードされたファイルがアクセスされるフォルダパス
collections:
  - name: "post"
    label: "Post"
    folder: "content/post"
    create: true
    fields: # 管理画面に追加したいフォームを追加していく
      - {label: "タイトル", name: "title", widget: "string"}
      - {label: "サブタイトル", name: "subtitle", widget: "string", required: false}
      - {label: "タグ", name: "tags", widget: "text", required: false}
      - {label: "本文", name: "body", widget: "markdown", required: false}
      - {label: "画像", name: "image", widget: "image",media_library: {config: {multiple: true}}, required: false}
